"""add_admin_columns_to_users

Revision ID: 99130406ee22
Revises: 001_add_verification_tokens
Create Date: 2025-08-03 15:22:21.658227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99130406ee22'
down_revision = '001_add_verification_tokens'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvases', sa.Column('palette_type', sa.String(length=20), nullable=True))
    op.add_column('canvases', sa.Column('collaboration_mode', sa.String(length=20), nullable=True))
    op.add_column('canvases', sa.Column('auto_save_interval', sa.Integer(), nullable=True))
    op.add_column('canvases', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('canvases', sa.Column('is_moderated', sa.Boolean(), nullable=True))
    op.add_column('canvases', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('admin_permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_permissions')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_admin')
    op.drop_column('canvases', 'creator_id')
    op.drop_column('canvases', 'is_moderated')
    op.drop_column('canvases', 'is_public')
    op.drop_column('canvases', 'auto_save_interval')
    op.drop_column('canvases', 'collaboration_mode')
    op.drop_column('canvases', 'palette_type')
    # ### end Alembic commands ### 